# Auto-generated by compose2nix.

{ config, pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."n8n" = {
    image = "n8nio/n8n:latest";
    environmentFiles = [
      config.age.secrets.n8n.path
    ];
    environment = {
      "DB_SQLITE_POOL_SIZE" = "2";
      "GENERIC_TIMEZONE" = "Asia/Kolkata";
      "N8N_BLOCK_ENV_ACCESS_IN_NODE" = "false";
      "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS" = "true";
      "N8N_GIT_NODE_DISABLE_BARE_REPOS" = "true";
      "N8N_RUNNERS_ENABLED" = "true";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/virajs-server/docker/n8n/data:/home/node/.n8n:rw"
    ];
    ports = [
      "5678:5678/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=n8n"
      "--network=nginx"
    ];
  };
  systemd.services."docker-n8n" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-n8n-root.target"
    ];
    wantedBy = [
      "docker-compose-n8n-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-n8n-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
