# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."n8n-n8n" = {
    image = "docker.n8n.io/n8nio/n8n";
    environment = {
      "DB_POSTGRESDB_DATABASE" = "n8n";
      "DB_POSTGRESDB_HOST" = "postgres";
      "DB_POSTGRESDB_PASSWORD" = "Shirodkar@45";
      "DB_POSTGRESDB_PORT" = "5432";
      "DB_POSTGRESDB_USER" = "virajs";
      "DB_TYPE" = "postgresdb";
    };
    volumes = [
      "/home/virajs-server/docker/n8n/data/n8n_storage:/home/node/.n8n:rw"
    ];
    ports = [
      "1010:5678/tcp"
    ];
    dependsOn = [
      "n8n-postgres"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=n8n"
      "--network=nginx"
    ];
  };
  systemd.services."docker-n8n-n8n" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-n8n-root.target"
    ];
    wantedBy = [
      "docker-compose-n8n-root.target"
    ];
  };
  virtualisation.oci-containers.containers."n8n-postgres" = {
    image = "postgres:16";
    environment = {
      "POSTGRES_DB" = "n8n";
      "POSTGRES_NON_ROOT_PASSWORD" = "Shirodkar@45";
      "POSTGRES_NON_ROOT_USER" = "virajs";
      "POSTGRES_PASSWORD" = "Shirodkar@45";
      "POSTGRES_USER" = "virajs";
    };
    volumes = [
      "/home/virajs-server/docker/n8n/data/db_storage:/var/lib/postgresql/data:rw"
      "/home/virajs-server/docker/n8n/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -h localhost -U virajs -d n8n"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=postgres"
      "--network=nginx"
    ];
  };
  systemd.services."docker-n8n-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-n8n-root.target"
    ];
    wantedBy = [
      "docker-compose-n8n-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-n8n-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
