# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."moodle-mariadb" = {
    image = "mariadb";
    environment = {
      "MYSQL_DATABASE" = "moodle";
      "MYSQL_ROOT_PASSWORD" = "moodle";
      "MYSQL_ROOT_USER" = "root";
    };
    volumes = [
      "/home/virajs-server/docker/moodle/srv/Configs/Databases/Moodle:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mariadb"
      "--network=nginx"
    ];
  };
  systemd.services."docker-moodle-mariadb" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-moodle-root.target"
    ];
    wantedBy = [
      "docker-compose-moodle-root.target"
    ];
  };
  virtualisation.oci-containers.containers."moodle" = {
    image = "bitnami/moodle:latest";
    environment = {
      "MOODLE_DATABASE_HOST" = "mariadb";
      "MOODLE_DATABASE_NAME" = "moodle";
      "MOODLE_DATABASE_PASSWORD" = "moodle";
      "MOODLE_DATABASE_USER" = "root";
      "PGID" = "100";
      "PUID" = "998";
    };
    volumes = [
      "/home/virajs-server/docker/moodle/srv/Configs/Moodle:/bitnami/moodle:rw"
      "/home/virajs-server/docker/moodle/srv/Configs/MoodleData:/bitnami/moodledata:rw"
    ];
    dependsOn = [
      "moodle-mariadb"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=moodle"
      "--network=nginx"
    ];
  };
  systemd.services."docker-moodle" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-moodle-root.target"
    ];
    wantedBy = [
      "docker-compose-moodle-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-moodle-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
