# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."tiny10" = {
    image = "dockurr/windows";
    environment = {
      "CPU_CORES" = "2";
      "DISK_SIZE" = "100G";
      "PASSWORD" = "test@123";
      "RAM_SIZE" = "8G";
      "USERNAME" = "virajs";
      "VERSION" = "10";
    };
    volumes = [
      "/home/virajs-server/docker/nextcloud/data/virajs/files/Storage/iso/tiny10_23h2_x64.iso:/boot.iso:rw"
      "/home/virajs-server/docker/nextcloud/data/virajs/files/Storage/tiny10-shared:/shared:rw"
      "/home/virajs-server/docker/tiny10/data/windows:/storage:rw"
    ];
    ports = [
      "8006:8006/tcp"
      "3389:3389/tcp"
      "3389:3389/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/kvm:/dev/kvm:rwm"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=windows"
      "--network=nginx"
    ];
  };
  systemd.services."docker-tiny10" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-tiny10-root.target"
    ];
    wantedBy = [
      "docker-compose-tiny10-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-tiny10-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
