# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."nextcloud" = {
    image = "lscr.io/linuxserver/nextcloud:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/virajs-server/docker/nextcloud/config:/config:rw"
      "/home/virajs-server/docker/nextcloud/data:/data:rw"
    ];
    ports = [
      "1005:443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=nextcloud"
      "--network=nginx"
    ];
  };
  systemd.services."docker-nextcloud" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-nextcloud-root.target"
    ];
    wantedBy = [
      "docker-compose-nextcloud-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-nextcloud-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
