# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "jellyfin/jellyfin";
    environment = {
      "JELLYFIN_PublishedServerUrl" = "https://jellyfin.viraj.top";
    };
    volumes = [
      "/home/virajs-server/docker/jellyfin/data/cache:/cache:rw"
      "/home/virajs-server/docker/jellyfin/data/config:/config:rw"
      "/home/virajs-server/docker/jellyfin/data/fonts:/usr/local/share/fonts/custom:ro"
      "/home/virajs-server/docker/jellyfin/data/media:/media:rw"
      "/home/virajs-server/docker/jellyfin/data/media2:/media2:ro"
    ];
    user = "1000:1000";
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=jellyfin"
      "--network=nginx"
    ];
  };
  systemd.services."docker-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-jellyfin-root.target"
    ];
    wantedBy = [
      "docker-compose-jellyfin-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
