# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."mydylms-client" = {
    image = "virajsh/mydylms-client:latest";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mydylms-client"
      "--network=nginx"
    ];
  };
  systemd.services."docker-mydylms-client" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-mydylms-client-root.target"
    ];
    wantedBy = [
      "docker-compose-mydylms-client-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-mydylms-client-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
