# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."navidrome-navidrome" = {
    image = "deluan/navidrome:latest";
    volumes = [
      "/home/virajs-server/docker/navidrome/data/data:/data:rw"
      "/home/virajs-server/docker/nextcloud/data/virajs/files/Music:/music:ro"
    ];
    user = "1000:1000";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=navidrome"
      "--network=nginx"
    ];
  };
  systemd.services."docker-navidrome-navidrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-navidrome-root.target"
    ];
    wantedBy = [
      "docker-compose-navidrome-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-navidrome-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
