# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ntfy" = {
    image = "binwiederhier/ntfy";
    environment = {
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/virajs-server/docker/ntfy/data/etc/ntfy:/etc/ntfy:rw"
      "/home/virajs-server/docker/ntfy/data/var/cache/ntfy:/var/cache/ntfy:rw"
    ];
    ports = [
      "1015:80/tcp"
    ];
    cmd = [ "serve" ];
    user = "1000:1000";
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=wget -q --tries=1 http://localhost:1015/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-start-period=40s"
      "--health-timeout=10s"
      "--network-alias=ntfy"
      "--network=nginx"
    ];
  };
  systemd.services."docker-ntfy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-ntfy-root.target"
    ];
    wantedBy = [
      "docker-compose-ntfy-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ntfy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
