# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."karakeep-chrome" = {
    image = "gcr.io/zenika-hub/alpine-chrome:124";
    cmd = [ "--no-sandbox" "--disable-gpu" "--disable-dev-shm-usage" "--remote-debugging-address=0.0.0.0" "--remote-debugging-port=9222" "--hide-scrollbars" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=chrome"
      "--network=nginx"
    ];
  };
  systemd.services."docker-karakeep-chrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-karakeep-root.target"
    ];
    wantedBy = [
      "docker-compose-karakeep-root.target"
    ];
  };
  virtualisation.oci-containers.containers."karakeep-meilisearch" = {
    image = "getmeili/meilisearch:v1.13.3";
    environment = {
      "BROWSER_WEB_URL" = "http://chrome:9222";
      "DATA_DIR" = "/data";
      "KARAKEEP_VERSION" = "release";
      "MEILI_ADDR" = "http://meilisearch:7700";
      "MEILI_MASTER_KEY" = "IV3JlwV#Gz";
      "MEILI_NO_ANALYTICS" = "true";
      "NEXTAUTH_SECRET" = "aF9Q^dbXN#";
      "NEXTAUTH_URL" = "https://karakeep.viraj.top";
      "OPENAI_API_KEY" = "your_openai_api_key_here";
    };
    volumes = [
      "/home/virajs-server/docker/karakeep/data/meilisearch:/meili_data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=meilisearch"
      "--network=nginx"
    ];
  };
  systemd.services."docker-karakeep-meilisearch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-karakeep-root.target"
    ];
    wantedBy = [
      "docker-compose-karakeep-root.target"
    ];
  };
  virtualisation.oci-containers.containers."karakeep-web" = {
    image = "ghcr.io/karakeep-app/karakeep:release";
    environment = {
      "BROWSER_WEB_URL" = "http://chrome:9222";
      "DATA_DIR" = "/data";
      "KARAKEEP_VERSION" = "release";
      "MEILI_ADDR" = "http://meilisearch:7700";
      "MEILI_MASTER_KEY" = "IV3JlwV#Gz";
      "NEXTAUTH_SECRET" = "aF9Q^dbXN#";
      "NEXTAUTH_URL" = "https://karakeep.viraj.top";
      "OPENAI_API_KEY" = "your_openai_api_key_here";
    };
    volumes = [
      "/home/virajs-server/docker/karakeep/data:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=web"
      "--network=nginx"
    ];
  };
  systemd.services."docker-karakeep-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-karakeep-root.target"
    ];
    wantedBy = [
      "docker-compose-karakeep-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-karakeep-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
