# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = "vaultwarden/server:latest";
    environment = {
      "DOMAIN" = "https://localhost:1000";
    };
    volumes = [
      "/home/virajs-server/docker/vaultwarden/data/:/data:rw"
    ];
    ports = [
      "127.0.0.1:1000:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vaultwarden"
      "--network=vaultwarden_default"
    ];
  };
  systemd.services."docker-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-vaultwarden_default.service"
    ];
    requires = [
      "docker-network-vaultwarden_default.service"
    ];
    partOf = [
      "docker-compose-vaultwarden-root.target"
    ];
    wantedBy = [
      "docker-compose-vaultwarden-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-vaultwarden_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f vaultwarden_default";
    };
    script = ''
      docker network inspect vaultwarden_default || docker network create vaultwarden_default
    '';
    partOf = [ "docker-compose-vaultwarden-root.target" ];
    wantedBy = [ "docker-compose-vaultwarden-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vaultwarden-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
