# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."filebrowser" = {
    image = "filebrowser/filebrowser:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "/home/virajs-server:/srv:rw"
      "/home/virajs-server/docker/filebrowser/data/filebrowser_config:/config:rw"
      "/home/virajs-server/docker/filebrowser/data/filebrowser_database:/database:rw"
      "/mnt/1TB_HDD:/srv/1TB_HDD:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=filebrowser"
      "--network=nginx"
    ];
  };
  systemd.services."docker-filebrowser" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-filebrowser-root.target"
    ];
    wantedBy = [
      "docker-compose-filebrowser-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-filebrowser-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
