# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  # virtualisation.docker = {
  #   enable = true;
  #   autoPrune.enable = true;
  # };
  # virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."brave" = {
    image = "lscr.io/linuxserver/brave:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/virajs-server/nix-conf/compose/brave/data/config:/config:rw"
    ];
    ports = [
      "3000:3000/tcp"
      "3001:3001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=brave"
      "--network=caddy"
      "--shm-size=1073741824"
    ];
  };
  systemd.services."docker-brave" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-brave-root.target"
    ];
    wantedBy = [
      "docker-compose-brave-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-brave-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
