name: intellijidea
services:
  intellij-idea:
    image: lscr.io/linuxserver/intellij-idea:latest
    container_name: intellij-idea
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/virajs-server/docker/intellij-idea/data/config:/config
    shm_size: "1gb"
    restart: "no"
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - nginx
networks:
  nginx:
    external: true
