# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."openvscode-server" = {
    image = "lscr.io/linuxserver/openvscode-server:latest";
    environment = {
      "CONNECTION_SECRET" = "";
      "CONNECTION_TOKEN" = "";
      "PGID" = "1000";
      "PUID" = "1000";
      "SUDO_PASSWORD" = "";
      "SUDO_PASSWORD_HASH" = "";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/virajs-server:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=openvscode-server"
      "--network=nginx"
    ];
  };
  systemd.services."docker-openvscode-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-vscode-root.target"
    ];
    wantedBy = [
      "docker-compose-vscode-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vscode-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
