# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."obsidian" = {
    image = "lscr.io/linuxserver/obsidian:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/virajs-server/docker/obsidian/data/config:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=obsidian"
      "--network=nginx"
      "--shm-size=1073741824"
    ];
  };
  systemd.services."docker-obsidian" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-obsidian-root.target"
    ];
    wantedBy = [
      "docker-compose-obsidian-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-obsidian-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
