# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ollama-3b" = {
    image = "ollama/ollama";
    environment = {
      "OLLAMA_HOST" = "0.0.0.0";
      "OLLAMA_KEEP_ALIVE" = "3h";
    };
    volumes = [
      "/home/virajs-server/docker/ollama/data/ollama1b:/root/.ollama:rw"
    ];
    ports = [
      "11434:11434/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=ollama-3b"
      "--network=nginx"
    ];
  };
  systemd.services."docker-ollama-3b" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-ollama-3b-root.target"
    ];
    wantedBy = [
      "docker-compose-ollama-3b-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ollama-3b-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
