# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."nexterm-nexterm" = {
    image = "germannewsmaker/nexterm:1.0.5-OPEN-PREVIEW";
    environment = {
      "ENCRYPTION_KEY" = "9de934ff1622782aa86009b0e830ec68b614bed46c8ae717ba91353faecc9272";
    };
    volumes = [
      "/home/virajs-server/docker/nexterm/data:/app/data:rw"
    ];
    ports = [
      "6989:6989/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=nexterm"
      "--network=nginx"
    ];
  };
  systemd.services."podman-nexterm-nexterm" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-nexterm-root.target"
    ];
    wantedBy = [
      "podman-compose-nexterm-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-nexterm-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
