# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."nexterm-nexterm" = {
    image = "germannewsmaker/nexterm:1.0.5-OPEN-PREVIEW";
    environment = {
      "ENCRYPTION_KEY" = "9de934ff1622782aa86009b0e830ec68b614bed46c8ae717ba91353faecc9272";
    };
    volumes = [
      "/home/virajs-server/docker/nexterm/data:/app/data:rw"
    ];
    ports = [
      "6989:6989/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=nexterm"
      "--network=nginx"
    ];
  };
  systemd.services."docker-nexterm-nexterm" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-nexterm-root.target"
    ];
    wantedBy = [
      "docker-compose-nexterm-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-nexterm-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
