# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."speedtest-tracker" = {
    image = "lscr.io/linuxserver/speedtest-tracker:latest";
    environment = {
      "APP_KEY" = "base64:HhypJCAGzAtQzHp5tNPcUe9thkdj/ztY5cj2WCYEy9o=";
      "APP_URL" = "https://speedtest.viraj.top";
      "DB_CONNECTION" = "sqlite";
      "DISPLAY_TIMEZONE" = "Asia/Kolkata";
      "PGID" = "1000";
      "PRUNE_RESULTS_OLDER_THAN" = "0";
      "PUID" = "1000";
      "SPEEDTEST_SCHEDULE" = "0 * * * *";
      "SPEEDTEST_SERVERS" = "";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/home/virajs-server/docker/speedtest-tracker/data/speedtest-tracker/data:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=speedtest-tracker"
      "--network=nginx"
    ];
  };
  systemd.services."docker-speedtest-tracker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-speedtesttracker-root.target"
    ];
    wantedBy = [
      "docker-compose-speedtesttracker-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-speedtesttracker-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
