name: jupyterhub
services:
  jupyterhub:
    image: quay.io/jupyterhub/jupyterhub:latest
    container_name: jupyterhub
    restart: "no"
    command: jupyterhub
    ports:
      - "${JUPYTERHUB_PORT}:8000"
    volumes:
      - /home/virajs-server/docker/jupyterhub/data:/srv/jupyterhub
      - /home/virajs-server/docker/jupyterhub/data/py:/home/virajs
    networks:
      - nginx

networks:
  nginx:
    external: true 