name: obsidian
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/virajs-server/docker/obsidian/data/config:/config
    # ports:
    #   - ${OBSIDIAN_PORT_1}:3000
    #   - ${OBSIDIAN_PORT_2}:3001
    shm_size: "1gb"
    restart: "no"
    networks:
      - nginx
networks:
  nginx:
    external: true    