# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."glance" = {
    image = "glanceapp/glance";
    environment = {
      "MY_SECRET_TOKEN" = "123456";
    };
    volumes = [
      "/etc/localtime:/etc/localtime:ro"
      "/home/virajs-server/docker/glance/assets:/app/assets:rw"
      "/home/virajs-server/docker/glance/config:/app/config:rw"
      "/var/run/docker.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "8089:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=glance"
      "--network=nginx"
    ];
  };
  systemd.services."docker-glance" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-glance-root.target"
    ];
    wantedBy = [
      "docker-compose-glance-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-glance-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
