# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."expenseowl" = {
    image = "tanq16/expenseowl:main";
    volumes = [
      "/home/virajs-server/docker/expenseowl/data:/app/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=expenseowl"
      "--network=nginx"
    ];
  };
  systemd.services."docker-expenseowl" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-expenseowl-root.target"
    ];
    wantedBy = [
      "docker-compose-expenseowl-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-expenseowl-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
