# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jupyterhub" = {
    image = "quay.io/jupyterhub/jupyterhub:latest";
    volumes = [
      "/home/virajs-server/docker/jupyterhub/data:/srv/jupyterhub:rw"
      "/home/virajs-server/docker/jupyterhub/data/py:/home/virajs:rw"
    ];
    ports = [
      "27843:8000/tcp"
    ];
    cmd = [ "jupyterhub" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=jupyterhub"
      "--network=nginx"
    ];
  };
  systemd.services."docker-jupyterhub" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-jupyterhub-root.target"
    ];
    wantedBy = [
      "docker-compose-jupyterhub-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jupyterhub-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
