# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."stirlingpdf-stirling-pdf" = {
    image = "docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest";
    environment = {
      "DISABLE_ADDITIONAL_FEATURES" = "false";
      "LANGS" = "en_GB";
    };
    volumes = [
      "/home/virajs-server/docker/stirlingpdf/data/customFiles:/customFiles:rw"
      "/home/virajs-server/docker/stirlingpdf/data/extraConfigs:/configs:rw"
      "/home/virajs-server/docker/stirlingpdf/data/logs:/logs:rw"
      "/home/virajs-server/docker/stirlingpdf/data/pipeline:/pipeline:rw"
      "/home/virajs-server/docker/stirlingpdf/data/trainingData:/usr/share/tessdata:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=stirling-pdf"
      "--network=nginx"
    ];
  };
  systemd.services."docker-stirlingpdf-stirling-pdf" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    partOf = [
      "docker-compose-stirlingpdf-root.target"
    ];
    wantedBy = [
      "docker-compose-stirlingpdf-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-stirlingpdf-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
