# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."beszel" = {
    image = "henrygd/beszel:latest";
    volumes = [
      "/home/virajs-server/docker/beszel/data/beszel_data:/beszel_data:rw"
      "/home/virajs-server/docker/beszel/data/beszel_socket:/beszel_socket:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=beszel"
      "--network=nginx"
    ];
  };
  systemd.services."docker-beszel" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-beszel-root.target"
    ];
    wantedBy = [
      "docker-compose-beszel-root.target"
    ];
  };
  virtualisation.oci-containers.containers."beszel-agent" = {
    image = "henrygd/beszel-agent:latest";
    environment = {
      "HUB_URL" = "https://beszel.viraj.top";
      "KEY" = "";
      "LISTEN" = "/beszel_socket/beszel.sock";
    };
    volumes = [
      "/home/virajs-server/docker/beszel/data/beszel_agent_data:/var/lib/beszel-agent:rw"
      "/home/virajs-server/docker/beszel/data/beszel_socket:/beszel_socket:rw"
      "/var/run/docker.sock:/var/run/docker.sock:ro"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."docker-beszel-agent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-beszel-root.target"
    ];
    wantedBy = [
      "docker-compose-beszel-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-beszel-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
