# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."vikunja" = {
    image = "vikunja/vikunja";
    environment = {
      "VIKUNJA_DATABASE_DATABASE" = "vikunja";
      "VIKUNJA_DATABASE_HOST" = "vikunja-db";
      "VIKUNJA_DATABASE_PASSWORD" = "Shirodkar@45";
      "VIKUNJA_DATABASE_TYPE" = "mysql";
      "VIKUNJA_DATABASE_USER" = "vikunja";
      "VIKUNJA_SERVICE_JWTSECRET" = "3spU8so3jfoKktY+Lw==";
      "VIKUNJA_SERVICE_PUBLICURL" = "https://vikunja.viraj.top/";
    };
    volumes = [
      "/home/virajs-server/docker/vikunja/files:/app/vikunja/files:rw"
    ];
    dependsOn = [
      "vikunja-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=vikunja"
      "--network=nginx"
    ];
  };
  systemd.services."docker-vikunja" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-vikunja-root.target"
    ];
    wantedBy = [
      "docker-compose-vikunja-root.target"
    ];
  };
  virtualisation.oci-containers.containers."vikunja-db" = {
    image = "mariadb:10";
    environment = {
      "MYSQL_DATABASE" = "vikunja";
      "MYSQL_PASSWORD" = "Shirodkar@45";
      "MYSQL_ROOT_PASSWORD" = "Shirodkar@45";
      "MYSQL_USER" = "vikunja";
    };
    volumes = [
      "/home/virajs-server/docker/vikunja/db:/var/lib/mysql:rw"
    ];
    cmd = [ "--character-set-server=utf8mb4" "--collation-server=utf8mb4_unicode_ci" ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=mysqladmin ping -h localhost -u $MYSQL_USER --password=$MYSQL_PASSWORD"
      "--health-interval=2s"
      "--health-start-period=30s"
      "--network-alias=db"
      "--network=nginx"
    ];
  };
  systemd.services."docker-vikunja-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-vikunja-root.target"
    ];
    wantedBy = [
      "docker-compose-vikunja-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vikunja-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
