# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  ...
}: {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."cloudflared-tun1" = {
    image = "cloudflare/cloudflared:latest";
    environment = {
      "TOKEN" = "eyJhIjoiNGNlOTNhNjM5OGNlMzQzNTY3NjI2MGU4N2VhMWZlYTEiLCJ0IjoiODA3MWU2YjEtMmI4OS00YzY0LTg5NjQtNmJiMDNkMTc2YWUwIiwicyI6Ik5UWmlOMlF4TTJRdFpESmpOUzAwTXpZeUxUazJZVGt0TXpNNVpEVXpOVE15TWpjeCJ9";
    };
    cmd = ["tunnel" "--no-autoupdate" "run" "--token" "eyJhIjoiNGNlOTNhNjM5OGNlMzQzNTY3NjI2MGU4N2VhMWZlYTEiLCJ0IjoiODA3MWU2YjEtMmI4OS00YzY0LTg5NjQtNmJiMDNkMTc2YWUwIiwicyI6Ik5UWmlOMlF4TTJRdFpESmpOUzAwTXpZeUxUazJZVGt0TXpNNVpEVXpOVE15TWpjeCJ9"];
    log-driver = "journald";
    extraOptions = [
      "--network=host"
    ];
  };
  systemd.services."docker-cloudflared-tun1" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-cloudflared-root.target"
    ];
    wantedBy = [
      "docker-compose-cloudflared-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-cloudflared-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
