name: stirlingpdf
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    # ports:
    #   - '${STIRLING_PORT}:8080'
    volumes:
      - /home/virajs-server/docker/stirlingpdf/data/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /home/virajs-server/docker/stirlingpdf/data/extraConfigs:/configs
      - /home/virajs-server/docker/stirlingpdf/data/customFiles:/customFiles/
      - /home/virajs-server/docker/stirlingpdf/data/logs:/logs/
      - /home/virajs-server/docker/stirlingpdf/data/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
    networks:
      - nginx
networks:
  nginx:
    external: true      